auto_merge: false
backup_model: meta-llama/llama-3.1-8b-instruct:free
create_branches: true
enable_code_validation: true
enable_dependency_analysis: true
enable_documentation_generation: true
enable_performance_profiling: true
enable_testing_generation: true
fallback_model: google/gemini-2.0-flash-exp:free
max_code_length: 10000
max_concurrent_requests: 3
min_code_length: 50
primary_model: deepseek/deepseek-r1-0528-qwen3-8b:free
repo_name: WATCHDOG_memory
repo_owner: Sid7on1
request_timeout: 120
retry_attempts: 3
retry_delay: 2
temperature: 0.3
