name: Daily Automation Pipeline

on:
  schedule:
    # Runs daily at 1:30 AM IST (which is 8:00 PM UTC the previous day)
    - cron: '0 20 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  run-daily-automation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then 
          echo "Installing from requirements.txt..."
          pip install -r requirements.txt
          echo "Verifying PDF libraries installation..."
          python -c "import PyPDF2; print('PyPDF2 installed successfully')"
          python -c "import pdfplumber; print('pdfplumber installed successfully')"
        else
          echo "requirements.txt not found, installing essential packages..."
          pip install PyPDF2 pdfplumber requests python-dotenv
        fi
        
    - name: Set up environment variables
      env:
        OPEN_API: ${{ secrets.OPEN_API }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        cohere_API: ${{ secrets.COHERE_API }}
        groq_API: ${{ secrets.GROQ_API }}
        HF_API: ${{ secrets.HF_API }}
        GITHUB_API: ${{ secrets.API_GITHUB }}
      run: |
        echo "Environment variables configured from GitHub secrets"
        echo "Setting up environment for IST timezone"
        
    - name: Run scraper
      env:
        OPEN_API: ${{ secrets.OPEN_API }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        cohere_API: ${{ secrets.COHERE_API }}
        groq_API: ${{ secrets.GROQ_API }}
        HF_API: ${{ secrets.HF_API }}
        GITHUB_API: ${{ secrets.API_GITHUB }}
      run: |
        echo "Starting scraper..."
        python scraper.py || { echo "Scraper failed with exit code $?"; exit 1; }
      
    - name: Run extractor
      env:
        OPEN_API: ${{ secrets.OPEN_API }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        cohere_API: ${{ secrets.COHERE_API }}
        groq_API: ${{ secrets.GROQ_API }}
        HF_API: ${{ secrets.HF_API }}
        GITHUB_API: ${{ secrets.API_GITHUB }}
      run: |
        echo "Starting extractor..."
        python extractor.py || { echo "Extractor failed with exit code $?"; exit 1; }
      
    - name: Run planner
      env:
        OPEN_API: ${{ secrets.OPEN_API }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        cohere_API: ${{ secrets.COHERE_API }}
        groq_API: ${{ secrets.GROQ_API }}
        HF_API: ${{ secrets.HF_API }}
        GITHUB_API: ${{ secrets.API_GITHUB }}
      run: |
        echo "Starting planner..."
        python planner.py || { echo "Planner failed with exit code $?"; exit 1; }
      
    - name: Run manager (runs 4 coders automatically)
      env:
        OPEN_API: ${{ secrets.OPEN_API }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        cohere_API: ${{ secrets.COHERE_API }}
        groq_API: ${{ secrets.GROQ_API }}
        HF_API: ${{ secrets.HF_API }}
        GITHUB_API: ${{ secrets.API_GITHUB }}
      run: |
        echo "Starting manager..."
        python manager.py || { echo "Manager failed with exit code $?"; exit 1; }

    - name: Run pusher
      env:
        OPEN_API: ${{ secrets.OPEN_API }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        cohere_API: ${{ secrets.COHERE_API }}
        groq_API: ${{ secrets.GROQ_API }}
        HF_API: ${{ secrets.HF_API }}
        GITHUB_API: ${{ secrets.API_GITHUB }}
      run: |
        echo "Starting pusher..."
        python pusher.py || { echo "Pusher failed with exit code $?"; exit 1; }
      
    - name: Upload logs (optional)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: automation-logs
        path: |
          *.log
          logs/
        retention-days: 7
