name: Daily Automation Pipeline

on:
  schedule:
    # Runs daily at 1:30 AM IST (which is 8:00 PM UTC the previous day)
    - cron: '0 20 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  run-daily-automation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Set up environment variables
      env:
        OPEN_API: ${{ secrets.OPEN_API }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        cohere_API: ${{ secrets.COHERE_API }}
        groq_API: ${{ secrets.GROQ_API }}
        HF_API: ${{ secrets.HF_API }}
        GITHUB_API: ${{ secrets.GITHUB_API }}
      run: |
        echo "Environment variables configured from GitHub secrets"
        echo "Setting up environment for IST timezone"
        
    - name: Run workflow orchestrator
      env:
        OPEN_API: ${{ secrets.OPEN_API }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        cohere_API: ${{ secrets.COHERE_API }}
        groq_API: ${{ secrets.GROQ_API }}
        HF_API: ${{ secrets.HF_API }}
        GITHUB_API: ${{ secrets.GITHUB_API }}
      run: python workflow_orchestrator.py
      
    - name: Run project tracker
      env:
        OPEN_API: ${{ secrets.OPEN_API }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        cohere_API: ${{ secrets.COHERE_API }}
        groq_API: ${{ secrets.GROQ_API }}
        HF_API: ${{ secrets.HF_API }}
        GITHUB_API: ${{ secrets.GITHUB_API }}
      run: python project_tracker.py
      
    - name: Run manager
      env:
        OPEN_API: ${{ secrets.OPEN_API }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        cohere_API: ${{ secrets.COHERE_API }}
        groq_API: ${{ secrets.GROQ_API }}
        HF_API: ${{ secrets.HF_API }}
        GITHUB_API: ${{ secrets.GITHUB_API }}
      run: python manager.py
      
    - name: Run planner
      env:
        OPEN_API: ${{ secrets.OPEN_API }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        cohere_API: ${{ secrets.COHERE_API }}
        groq_API: ${{ secrets.GROQ_API }}
        HF_API: ${{ secrets.HF_API }}
        GITHUB_API: ${{ secrets.GITHUB_API }}
      run: python planner.py
      
    - name: Run scraper
      env:
        OPEN_API: ${{ secrets.OPEN_API }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        cohere_API: ${{ secrets.COHERE_API }}
        groq_API: ${{ secrets.GROQ_API }}
        HF_API: ${{ secrets.HF_API }}
        GITHUB_API: ${{ secrets.GITHUB_API }}
      run: python scraper.py
      
    - name: Run extractor
      env:
        OPEN_API: ${{ secrets.OPEN_API }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        cohere_API: ${{ secrets.COHERE_API }}
        groq_API: ${{ secrets.GROQ_API }}
        HF_API: ${{ secrets.HF_API }}
        GITHUB_API: ${{ secrets.GITHUB_API }}
      run: python extractor.py
      
    - name: Run selector
      env:
        OPEN_API: ${{ secrets.OPEN_API }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        cohere_API: ${{ secrets.COHERE_API }}
        groq_API: ${{ secrets.GROQ_API }}
        HF_API: ${{ secrets.HF_API }}
        GITHUB_API: ${{ secrets.GITHUB_API }}
      run: python selector.py
      
    - name: Run status checker
      env:
        OPEN_API: ${{ secrets.OPEN_API }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        cohere_API: ${{ secrets.COHERE_API }}
        groq_API: ${{ secrets.GROQ_API }}
        HF_API: ${{ secrets.HF_API }}
        GITHUB_API: ${{ secrets.GITHUB_API }}
      run: python status_checker.py
      
    - name: Run coders
      env:
        OPEN_API: ${{ secrets.OPEN_API }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        cohere_API: ${{ secrets.COHERE_API }}
        groq_API: ${{ secrets.GROQ_API }}
        HF_API: ${{ secrets.HF_API }}
        GITHUB_API: ${{ secrets.GITHUB_API }}
      run: |
        python coder1.py
        python coder2.py
        python coder3.py
        python coder4.py
        
    - name: Run pusher
      env:
        OPEN_API: ${{ secrets.OPEN_API }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        cohere_API: ${{ secrets.COHERE_API }}
        groq_API: ${{ secrets.GROQ_API }}
        HF_API: ${{ secrets.HF_API }}
        GITHUB_API: ${{ secrets.GITHUB_API }}
      run: python pusher.py
      
    - name: Upload logs (optional)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: automation-logs
        path: |
          *.log
          logs/
        retention-days: 7
